### ISSUE TITLE
pkg_resources.ContextualVersionConflict: (beem 0.23.9 (/usr/local/lib/python3.6/site-packages), Requirement.parse('beem==0.24.19'), {'transmitter'})

### ISSUE THREAD

**Issue by gluneau** [emre/transmitter#8]
Can you help figure this error please?

docker run -t transmitter set --property hbd_interest_rate=2c01
```
╰─± docker run -t transmitter set --property hbd_interest_rate=2c01
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (beem 0.23.9 (/usr/local/lib/python3.6/site-packages), Requirement.parse('beem==0.24.19'), {'transmitter'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/transmitter", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'beem==0.24.19' distribution was not found and is required by transmitter
```

This is the build messages for reference

docker build -t transmitter .
```
╰─± docker build -t transmitter .
Sending build context to Docker daemon  137.2kB
Step 1/9 : FROM publysher/alpine-numpy
 ---> bd60ccc63866
Step 2/9 : COPY . /app
 ---> Using cache
 ---> 22e203cd09c0
Step 3/9 : RUN mkdir -v '/root/.transmitter/'
 ---> Using cache
 ---> 6ac839461b8d
Step 4/9 : RUN mv -v /app/config.json.docker /root/.transmitter/config.json
 ---> Using cache
 ---> 71aeae1a697c
Step 5/9 : WORKDIR /app
 ---> Using cache
 ---> 7c128f13d108
Step 6/9 : RUN apk add --no-cache gcc python3-dev libc-dev libressl-dev
 ---> Using cache
 ---> b4a39c16a551
Step 7/9 : RUN pip3 install requests beem==0.23.9
 ---> Using cache
 ---> 3c8d98c08f0d
Step 8/9 : RUN pip3 install -e . --no-deps
 ---> Using cache
 ---> 906ef88543e7
Step 9/9 : ENTRYPOINT ["transmitter"]
 ---> Using cache
 ---> ca81a064e8b5
Successfully built ca81a064e8b5
Successfully tagged transmitter:latest
```

**Comment by emre** [comment]
spotted the error in Dockerfile, will update it today.

**Comment by emre** [comment]
I've updated the Dockerfile with e1b8c2945807ea7b24c31130de7db6625f917455.

1. git pull origin master
2. rebuild the docker image
3. run the command

Note: You need to pass hbd_interest_rate like 300 instead of 2c01. It's automatically converted in the background.

**Comment by emre** [comment]
closing this, let me know if the issue persists.
