### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 11 column 29 (char 366)

### ISSUE THREAD

**Issue by gluneau** [emre/transmitter#9]
Is there something wrong with my config or it's something else?

Here is the error:
```bash
╰─± docker run -t transmitter set --property hbd_interest_rate=300
Traceback (most recent call last):
  File "/usr/local/bin/transmitter", line 11, in <module>
    load_entry_point('transmitter', 'console_scripts', 'transmitter')()
  File "/app/transmitter/main.py", line 259, in main
    peg_multiplier=args.peg_multiplier,
  File "/app/transmitter/main.py", line 35, in __init__
    self.config = self.get_config(config_file)
  File "/app/transmitter/main.py", line 87, in get_config
    config = json.loads(open(config_file).read())
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 11 column 29 (char 366)
```

Here is my config:

```json
{
    "NODES": [
        "https://hived.emre.sh"
    ],
    "WITNESS_ACCOUNT": "helo",
    "SIGNING_KEY": "5J...yP",
    "ACTIVE_KEY": "5J...4F",
    "DEFAULT_PROPERTIES": {
      "account_creation_fee": "3 HIVE",
      "maximum_block_size": 65536,
      "hbd_interest_rate": 300
    },
    "URL": "https://hive.blog/@helo"
}
```

**Comment by emre** [comment]
I think you built the Docker container while the config was empty. If you rebuild the container, it should be okay. 

Can you test it like that?

**Comment by emre** [comment]
I know, this is not very practical but every config needs a container rebuild. I should address that in the future. But for now, try the workaround.

**Comment by emre** [comment]
hah, never mind, you have the config OKAY but it seems the json is invalid. Can you try validating it with a tool like jsonlint? The pasted config looks good, but somehow Python can't parse it for your case.

**Comment by gluneau** [comment]
Indeed I must have at some point built the docker with an invalid json file.
Then I fiddle with it, but did not rebuild. So the docker always had the bad copy.


json is validated:

```bash
─ubuntu at witness in ~/transmitter on master✘✘✘ using 
╰─± jsonlint config.json.docker     
config.json.docker: ok
```

Rebuild the docker with a  new copy the config inside

```
╭─ubuntu at witness in ~/transmitter on master✘✘✘ using 
╰─± docker build -t transmitter .                                 
Sending build context to Docker daemon  146.4kB
Step 1/9 : FROM publysher/alpine-numpy
 ---> bd60ccc63866
Step 2/9 : COPY . /app
 ---> 4753940cd72f
Step 3/9 : RUN mkdir -v '/root/.transmitter/'
 ---> Running in 9f5388fe9952
created directory: '/root/.transmitter/'
Removing intermediate container 9f5388fe9952
 ---> cd5dc9cc4c96
Step 4/9 : RUN mv -v /app/config.json.docker /root/.transmitter/config.json
 ---> Running in 54039d29353f
'/app/config.json.docker' -> '/root/.transmitter/config.json'
Removing intermediate container 54039d29353f
 ---> a9df47c0c1c7
Step 5/9 : WORKDIR /app
 ---> Running in 0b6fb4f2ec24
Removing intermediate container 0b6fb4f2ec24
 ---> f1d4efe89280
Step 6/9 : RUN apk add --no-cache gcc python3-dev libc-dev libressl-dev
 ---> Running in 7d6207bc2983
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/22) Upgrading musl (1.1.18-r3 -> 1.1.18-r4)
(2/22) Upgrading libressl2.6-libcrypto (2.6.3-r0 -> 2.6.5-r0)
(3/22) Upgrading libressl2.6-libssl (2.6.3-r0 -> 2.6.5-r0)
(4/22) Installing binutils-libs (2.30-r2)
(5/22) Installing binutils (2.30-r2)
(6/22) Installing gmp (6.1.2-r1)
(7/22) Installing isl (0.18-r0)
(8/22) Installing libgomp (6.4.0-r5)
(9/22) Installing libatomic (6.4.0-r5)
(10/22) Installing pkgconf (1.3.10-r0)
(11/22) Installing libgcc (6.4.0-r5)
(12/22) Installing mpfr3 (3.1.5-r1)
(13/22) Installing mpc1 (1.0.3-r1)
(14/22) Installing libstdc++ (6.4.0-r5)
(15/22) Installing gcc (6.4.0-r5)
(16/22) Installing musl-dev (1.1.18-r4)
(17/22) Installing libc-dev (0.7.1-r0)
(18/22) Upgrading musl-utils (1.1.18-r3 -> 1.1.18-r4)
(19/22) Installing libressl2.6-libtls (2.6.5-r0)
(20/22) Installing libressl-dev (2.6.5-r0)
(21/22) Installing python3 (3.6.9-r1)
(22/22) Installing python3-dev (3.6.9-r1)
Executing busybox-1.27.2-r7.trigger
Executing ca-certificates-20171114-r0.trigger
OK: 223 MiB in 61 packages
Removing intermediate container 7d6207bc2983
 ---> f5d46b13eb08
Step 7/9 : RUN pip3 install requests beem==0.24.19
 ---> Running in 4f354258947b
Collecting requests
  Downloading https://files.pythonhosted.org/packages/29/c1/24814557f1d22c56d50280771a17307e6bf87b70727d975fd6b2ce6b014a/requests-2.25.1-py2.py3-none-any.whl (61kB)
Collecting beem==0.24.19
  Downloading https://files.pythonhosted.org/packages/7b/e5/632d9c5bfb5c3eb0696c1e7b8b42af7bb5a4075345e290506a882bef576c/beem-0.24.19-py2.py3-none-any.whl (404kB)
Collecting urllib3<1.27,>=1.21.1 (from requests)
  Downloading https://files.pythonhosted.org/packages/23/fc/8a49991f7905261f9ca9df5aa9b58363c3c821ce3e7f671895442b7100f2/urllib3-1.26.3-py2.py3-none-any.whl (137kB)
Collecting chardet<5,>=3.0.2 (from requests)
  Downloading https://files.pythonhosted.org/packages/19/c7/fa589626997dd07bd87d9269342ccb74b1720384a4d739a1872bd84fbe68/chardet-4.0.0-py2.py3-none-any.whl (178kB)
Collecting idna<3,>=2.5 (from requests)
  Downloading https://files.pythonhosted.org/packages/a2/38/928ddce2273eaa564f6f50de919327bf3a00f091b5baba8dfa9460f3a8a8/idna-2.10-py2.py3-none-any.whl (58kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading https://files.pythonhosted.org/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl (147kB)
Collecting Click (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl (82kB)
Collecting click-shell (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/98/eb/7e09db5154c52905a61b36518a7013dfba0450116aa75cef80bfc7af36a8/click_shell-2.0-py2.py3-none-any.whl
Collecting asn1crypto (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/b5/a8/56be92dcd4a5bf1998705a9b4028249fe7c9a035b955fe93b6a3e5b829f8/asn1crypto-1.4.0-py2.py3-none-any.whl (104kB)
Collecting pytz (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/70/94/784178ca5dd892a98f113cdd923372024dc04b8d40abe77ca76b5fb90ca6/pytz-2021.1-py2.py3-none-any.whl (510kB)
Collecting prettytable (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/26/1b/42b59a4038bc0442e3a0085bc0de385658131eef8a88946333f870559b09/prettytable-2.1.0-py3-none-any.whl
Collecting appdirs (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Collecting ecdsa (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/98/16/70be2716e24eaf5d81074bb3c05429d60292c2a96613a78ac3d69526ad2a/ecdsa-0.16.1-py2.py3-none-any.whl (104kB)
Collecting websocket-client (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/08/33/80e0d4f60e84a1ddd9a03f340be1065a2a363c47ce65c4bd3bae65ce9631/websocket_client-0.58.0-py2.py3-none-any.whl (61kB)
Collecting scrypt (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/57/02/040f517985d66e2b453ac1abf50e9e4fde64094f64029add8bbd28b6d331/scrypt-0.8.17.tar.gz (56kB)
Collecting diff-match-patch (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/c2/5a/9aa3b95a1d108b82fadb1eed4c3773d19069f765bd4c360a930e107138ee/diff_match_patch-20200713-py3-none-any.whl (61kB)
Collecting ruamel.yaml (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/7e/39/186f14f3836ac5d2a6a042c8de69988770e8b9abb537610edc429e4914aa/ruamel.yaml-0.16.12-py2.py3-none-any.whl (111kB)
Collecting pycryptodomex (from beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/82/e2/a0f9f5452a59bafaa3420585f22b58a8566c4717a88c139af2276bb5695d/pycryptodomex-3.10.1.tar.gz (3.8MB)
Collecting importlib-metadata; python_version < "3.8" (from prettytable->beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/3a/0d/af9e3dce6524461fa1e8327449f392edac8a3d880b4c91ce3e2d25450d03/importlib_metadata-3.7.0-py3-none-any.whl
Collecting wcwidth (from prettytable->beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/59/7c/e39aca596badaf1b78e8f547c807b04dae603a433d3e7a7e04d67f2ef3e5/wcwidth-0.2.5-py2.py3-none-any.whl
Collecting six>=1.9.0 (from ecdsa->beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Collecting ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.9" (from ruamel.yaml->beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/fa/a1/f9c009a633fce3609e314294c7963abe64934d972abea257dce16a15666f/ruamel.yaml.clib-0.2.2.tar.gz (179kB)
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->prettytable->beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->prettytable->beem==0.24.19)
  Downloading https://files.pythonhosted.org/packages/41/ad/6a4f1a124b325618a7fb758b885b68ff7b058eec47d9220a12ab38d90b1f/zipp-3.4.0-py3-none-any.whl
Building wheels for collected packages: scrypt, pycryptodomex, ruamel.yaml.clib
  Running setup.py bdist_wheel for scrypt: started
  Running setup.py bdist_wheel for scrypt: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/45/e1/2a/316876a1cb98b869445a0e5399fc3d904cd9f4b6ba098d2f7c
  Running setup.py bdist_wheel for pycryptodomex: started
  Running setup.py bdist_wheel for pycryptodomex: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/0d/3c/92/196c13d133fc08153d992f67cc257330ebf6dc9c4e312f5c91
  Running setup.py bdist_wheel for ruamel.yaml.clib: started
  Running setup.py bdist_wheel for ruamel.yaml.clib: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/25/bc/04/ca8b9b1f2dc762a1d66d0a9358b38b1c4ebe79ecdd5227bd11
Successfully built scrypt pycryptodomex ruamel.yaml.clib
Installing collected packages: urllib3, chardet, idna, certifi, requests, Click, click-shell, asn1crypto, pytz, typing-extensions, zipp, importlib-metadata, wcwidth, prettytable, appdirs, six, ecdsa, websocket-client, scrypt, diff-match-patch, ruamel.yaml.clib, ruamel.yaml, pycryptodomex, beem
Successfully installed Click-7.1.2 appdirs-1.4.4 asn1crypto-1.4.0 beem-0.24.19 certifi-2020.12.5 chardet-4.0.0 click-shell-2.0 diff-match-patch-20200713 ecdsa-0.16.1 idna-2.10 importlib-metadata-3.7.0 prettytable-2.1.0 pycryptodomex-3.10.1 pytz-2021.1 requests-2.25.1 ruamel.yaml-0.16.12 ruamel.yaml.clib-0.2.2 scrypt-0.8.17 six-1.15.0 typing-extensions-3.7.4.3 urllib3-1.26.3 wcwidth-0.2.5 websocket-client-0.58.0 zipp-3.4.0
You are using pip version 10.0.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 4f354258947b
 ---> b9ccf8cb1bc5
Step 8/9 : RUN pip3 install -e . --no-deps
 ---> Running in 90bb864f0de3
Obtaining file:///app
Installing collected packages: transmitter
  Running setup.py develop for transmitter
Successfully installed transmitter
You are using pip version 10.0.1, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Removing intermediate container 90bb864f0de3
 ---> e9f0ba4b8146
Step 9/9 : ENTRYPOINT ["transmitter"]
 ---> Running in 59222c0dc406
Removing intermediate container 59222c0dc406
 ---> ac0a8d45717b
Successfully built ac0a8d45717b
Successfully tagged transmitter:latest

Execution:

```bash
╭─ubuntu at witness in ~/transmitter on master✘✘✘ using 
╰─± docker run -t transmitter set --property hbd_interest_rate=300
INFO:transmitter.main:Connecting to the blockchain using mainnet.
INFO:transmitter.main:Got the SIGNING_KEY in the config file.
INFO:transmitter.main:Got the WITNESS_ACCOUNT in the config file.
INFO:transmitter.main:Got the URL in the config file.
INFO:transmitter.main:Operation broadcasted.
```

Success!

![image](https://user-images.githubusercontent.com/2903505/109895286-f558b900-7c5c-11eb-8f14-8d553f47941b.png)
